name: Python application

on:
  push:
    branches: [ "**" ]  # läuft auf ALLEN Branches direkt beim push
  pull_request:
    branches: [ "develop", "main" ] # prüft PRs gegen die Haupt-Branches

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # QA 1: Linting
    - name: Lint with flake8
      run: |
        # Stop bei Syntax-Fehlern
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # QA 2: Type Checking (Logikfehler einfangen)
    - name: Type check with mypy
      run: |
        mypy . --ignore-missing-imports

    # QA 3: Security Check = prüft Bibliotheken auf Lücken
    - name: Security check with safety # Wir nutzen '|| true', damit die Pipeline nicht sofort abbricht, falls aber wir dokumentieren es.
      run: |
        safety check || true

    # Der eigentliche Test-Lauf
    - name: Test with pytest
      run: |
        pytest